routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::redirect('/home', '/');

Route::get('/', 'EmployeeController@index')->name('home');

Auth::routes((['reset' => false, 'confirm' => false]));

Route::resource('employees', 'EmployeeController')->only(['index', 'show']);

app/Avatar.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Avatar extends Model
{
    protected $fillable = ['path'];

    public $timestamps = false;

    public function employee()
    {
    	return $this->belongsTo('App\Employee');
    }
}

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    public function avatar()
    {
    	return $this->hasOne('App\Avatar');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'api_token',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Api/EmployeeController.php
<?php

namespace App\Http\Controllers\Api;

use App\Avatar;
use App\Employee;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreEmployee;
use App\Http\Resources\EmployeeResource;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class EmployeeController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:api')->except(['index', 'show', 'search']);
    }

    public function index()
    {
        return EmployeeResource::collection(Employee::with('avatar')->get());
    }

    public function store(StoreEmployee $request)
    {         
        $employee = new Employee;
        $employee->full_name = $request->input('full_name');
        $employee->nick_name = $request->input('nick_name');
        $employee->birthdate = "{$request->input('year')}-{$request->input('month')}-{$request->input('date')}";
        $employee->age = Carbon::parse($employee->birthdate)->age;
        $employee->address = $request->input('address');
        $employee->phone_number = $request->input('phone_number');
        $employee->save();

        if ($request->has('avatar')) {
            $file = $request->file('avatar');

            $avatar = new Avatar;
            $avatar->path = Storage::putFileAs('avatars', $file, "{$employee->id}.{$file->guessExtension()}");
            $employee->avatar()->save($avatar);
        }

        $employee->avatar;

        return new EmployeeResource($employee);
    }

    public function show($id)
    {
        $employee = Employee::with('avatar')->find($id);

        if ($employee == null) {
            return response()->json([
                'message' => 'Employee not found.'
            ]);
        }

        return new EmployeeResource($employee);
    }

    public function update(Request $request, Employee $employee)
    {
        if ($request->has('avatar')) {
            $file = $request->file('avatar');

            Storage::delete($employee->avatar->path);
            
            $employee->avatar->path = Storage::putFileAs('avatars', $file, "{$employee->id}.{$file->guessExtension()}");
            $employee->avatar->save();
        }

        $employee->nick_name = $request->input('nick_name');
        $employee->address = $request->input('address');
        $employee->phone_number = $request->input('phone_number');
        $employee->save();

        return new EmployeeResource($employee);
    }

    public function destroy($id)
    {
        $employee = Employee::find($id);

        if ($employee == null) {
            return response()->json([
                'message' => 'Employee not exist.'
            ]);
        }

        Storage::delete($employee->avatar->path);

        $employeeFullName = $employee->full_name;

        $employee->delete();

        return response()->json([
            'action' => 'Firing Employee!',
            'full_name' => $employeeFullName,
        ]);
    }

    public function search(Request $request)
    {
        $employees = Employee::where('full_name', 'like', $request->input('employee_name') . '%')
                            ->orWhere('full_name', 'like', '%' . $request->input('employee_name'))
                            ->orWhere('full_name', 'like', '%' . $request->input('employee_name') . '%')
                            ->get();

        return EmployeeResource::collection($employees);
    }
}

app/Http/Controllers/Api/LoginController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Hash;

class LoginController extends Controller
{
    public function login(Request $request)
    {
    	$credentials = $request->only('email', 'password');

        if (Auth::attempt($credentials)) {
            Cache::add('userLogin', Auth::user());

            return redirect()->route('home');
        } 
        
        return redirect()->route('login');
    }
}

app/Http/Controllers/Api/RegisterController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserRequest;
use App\User;
use Illuminate\Auth\Events\Registered;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;

class RegisterController extends Controller
{
	public function register(UserRequest $request)
    {
        event(new Registered($user = $this->create($request->all())));

        Cache::add('registerSuccess', 'Registration Successful! Please Login!');

        return redirect()->route('login');
    }

    protected function create(array $data)
    {
        return User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => Hash::make($data['password']),
            'api_token' => Str::random(80),
        ]);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Employee;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;

class EmployeeController extends Controller
{
    public function index()
    {
        if (Cache::has('userLogin')) {
            $user = Cache::pull('userLogin');
            Auth::login($user);

            session()->flash('status', 'You are logged in!');

            return redirect()->route('home');
        }

        $employees = Employee::with('avatar')->get();

        return view('home', compact('employees'));
    }

    public function show(Employee $employee)
    {
        return view('employees.show', compact('employee'));
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Employee;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index()
    {
    }
}

resources/views/employees/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">Profile Page</div>

                    <div class="card-body">
                        <div class="card">
                            <div class="card-body card-body-profile-page">
                                <img class="avatar-show-page mb-4" src="{{ Storage::url($employee->avatar->path) }}">
                                <h5 class="card-title font-weight-bold text-center">{{ $employee->full_name }} <span class="nick-name font-weight-normal">({{ $employee->nick_name }})</span></h5>
                                <h6 class="card-subtitle mb-4 text-muted text-center">Employee</h6>
                                <p class="card-text text-center">Currently {{ $employee->age }} years old, and has been an employee since {{ $employee->created_at->diffForHumans() }}.</p>
                                <p class="card-text text-center address">Address : {{ $employee->address }}</p>
                                <p class="card-text text-center phone-number">Phone Number : {{ $employee->phone_number }}</p>
                                
                                @auth
                                    <div class="row justify-content-center">
                                        <div class="col-md-2">
                                            <button class="btn btn-primary btn-block" data-toggle="modal" data-target="#modalUpdateEmployee">Update</button>
                                        </div>
                                        <div class="col-md-2">
                                            <form class="delete-employee-form" id="{{ $employee->id }}" method="post" action="{{ route('api.employees.destroy', ['employee' => $employee->id]) }}">
                                                @csrf
                                                @method('DELETE')
                    
                                                <input type="hidden" class="api_token" name="api_token" value="{{ Auth::user()->api_token }}">

                                                <button class="btn btn-danger btn-block" type="submit">Fire</button>
                                            </form>                                        
                                        </div>
                                    </div>
                                @endauth

                            </div>
                        </div>
    
                    </div>


                </div>
            </div>
        </div>
    </div>

    @auth
        <!-- Modal Update Employee -->
        
        <div class="modal fade bd-example-modal-lg" id="modalUpdateEmployee" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header bg-dark text-white">
                        <h5 class="modal-title" id="exampleModalLongTitle">Update Employee</h5>
                        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form class="update-employee-form" id="{{ $employee->id }}" method="post" action="{{ route('api.employees.update', ['employee' => $employee->id]) }}" enctype="multipart/form-data">
                            @csrf
                            @method('put')

                            <div class="form-group">
                                <label class="label-input-avatar" for="inputAvatar">Avatar</label>
                                <img class="avatar-modal mb-2" src="{{ Storage::url($employee->avatar->path) }}">
                                <input type="file" class="form-control-file input-change-avatar" name="avatar" id="inputAvatar">
                            </div>                        

                            <input type="hidden" class="api_token" name="api_token" value="{{ Auth::user()->api_token }}">

                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="inputName">Full Name</label>
                                    <input type="text" class="form-control" name="full_name" id="inputName" placeholder="Full Name" value="{{ $employee->full_name }}" readonly>
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="inputNickName">Nick Name</label>
                                    <input type="text" class="form-control" name="nick_name" id="inputNickName" placeholder="Nick Name" value="{{ $employee->nick_name }}">
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <label for="inputBirthdate">Date</label>
                                    <input type="text" class="form-control" name="birthdate" id="inputBirthdate" value="{{ $employee->birthdate }}" readonly="">
                                </div>
                            </div>
                            
                            <div class="form-group">
                                <label for="inputAddress">Address</label>
                                <input type="text" class="form-control" name="address" id="inputAddress" placeholder="Address" value="{{ $employee->address }}">
                            </div>
                            
                            <div class="form-group">
                                <label for="inputPhoneNumber">Phone Number</label>
                                <input type="text" class="form-control" name="phone_number" id="inputPhoneNumber" placeholder="Phone Number" value="{{ $employee->phone_number }}">
                            </div>
                    </div>
                    <div class="modal-footer">
                            <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-dark">Update Employee</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        <!-- End Modal Update Employee -->
    @endauth
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        
        <div class="row justify-content-center">
            <div class="col-md-11">
                @if (Session::has('status'))
                    <div class="alert alert-success" role="alert">
                        {{ Session::get('status') }}
                    </div>
                @endif                
            </div>
        </div>

        <div class="row justify-content-center">
            <div class="col-md-11">
                <div class="card">
                    <div class="card-header">Employee List</div>

                    <div class="card-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Avatar</th>                                        
                                    <th scope="col">Full Name</th>
                                    <th scope="col">Nick Name</th>
                                    <th scope="col">Age</th>
                                    <th scope="col">Birthdate</th>
                                    <th scope="col">Address</th>
                                    <th scope="col">Phone Number</th>
                                </tr>
                            </thead>
                            <tbody class="employee-table-body">
                                @forelse ($employees as $employee)
                                    <tr>
                                        <th scope="row" class="employee-num">{{ $loop->iteration }}</th>
                                        <td><img class="avatar" src="{{ Storage::url($employee->avatar->path) }}"></td>
                                        <td><a href="{{ route('employees.show', ['employee' => $employee->id]) }}">{{ $employee->full_name }}</a></td>
                                        <td>{{ $employee->nick_name }}</td>
                                        <td>{{ $employee->age }}</td>
                                        <td>{{ $employee->birthdate }}</td>
                                        <td>{{ $employee->address }}</td>
                                        <td>{{ $employee->phone_number }}</td>
                                    </tr>
                                @empty
                                    <p class="no-employees">There are currently no registered employees.</p>
                                @endforelse
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="https://kit.fontawesome.com/9dec657e70.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Merriweather:300,400,700|Montserrat:300,400,500,700&display=swap" rel="stylesheet">

    <!-- Styles -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/app.css') }}">
    <link rel="icon" type="image/png" href="{{ asset('img/logo.png') }}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3 mb-5">
        <div class="container">
            <a class="navbar-brand" href="{{ route('home') }}">PT Bumi Sentosa</a>
            @auth
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('home') }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" data-toggle="modal" data-target="#modalAddEmployee">Add Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" data-toggle="modal" data-target="#modalSearchEmployee">Search Employee</a>
                        </li>
                    </ul>
                </div>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <div class="dropdown show">
                            <li class="dropdown-toggle text-white user-dropdown" id="dropdownUser" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ Auth::user()->name }}
                            </li>
                            <div class="dropdown-menu" aria-labelledby="dropdownUser">
                                <form class="logout-form d-none" method="post" action="{{ route('logout') }}">
                                    @csrf
                                </form>
                                <a class="dropdown-item logout-link" href="#">Logout</a>
                            </div>
                        </div>
                    </ul>
                </div>
            @else
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">Register</a>
                        </li>
                    </ul>
                </div>            
            @endauth            
        </div>
    </nav>

    @yield('content')
    
    @auth
        
        <!-- Modal Add Employee -->

        <div class="modal fade bd-example-modal-lg" id="modalAddEmployee" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header bg-dark text-white">
                        <h5 class="modal-title" id="exampleModalLongTitle">Add New Employee</h5>
                        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form class="create-employee-form" method="post" action="{{ route('api.employees.store') }}" enctype="multipart/form-data">
                            @csrf

                            <input type="hidden" class="api_token" name="api_token" value="{{ Auth::user()->api_token }}">

                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="inputName">Full Name</label>
                                    <input type="text" class="form-control" name="full_name" id="inputName" placeholder="Full Name">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="inputNickName">Nick Name</label>
                                    <input type="text" class="form-control" name="nick_name" id="inputNickName" placeholder="Nick Name">
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="inputDate">Date</label>
                                    <input type="text" class="form-control" name="date" id="inputDate" placeholder="1-31">
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="inputMonth">Month</label>
                                    <input type="text" class="form-control" name="month" id="inputMonth" placeholder="1-12">
                                </div>
                                <div class="form-group col-md-2">
                                    <label for="inputYear">Year</label>
                                    <select id="inputYear" class="form-control" name="year">
                                        <option selected>Choose...</option>
                                        @for ($i = 1950; $i <= 2020; $i++)
                                            <option value="{{ $i }}">{{ $i }}</option>
                                        @endfor
                                    </select>
                                </div>
                            </div>
                            
                            <div class="form-group">
                                <label for="inputAddress">Address</label>
                                <input type="text" class="form-control" name="address" id="inputAddress" placeholder="Address">
                            </div>
                            
                            <div class="form-group">
                                <label for="inputPhoneNumber">Phone Number</label>
                                <input type="text" class="form-control" name="phone_number" id="inputPhoneNumber" placeholder="Phone Number">
                            </div>
                            
                            <div class="form-group">
                                <label for="inputAvatar">Avatar</label>
                                <input type="file" class="form-control-file" name="avatar" id="inputAvatar">
                            </div>                        
                    </div>
                    <div class="modal-footer">
                            <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-dark">Add Employee</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        <!-- End Modal Add Employee -->

        <!-- Modal Search Employee -->  

        <div class="modal fade bd-example-modal-lg" id="modalSearchEmployee" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header bg-dark">
                        <h5 class="modal-title text-white" id="exampleModalLabel">Search Employee</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span class="text-white" aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form class="search-employee-form" method="post" action="{{ route('api.employees.search') }}">
                            @csrf

                            <input class="form-control mr-sm-2" name="employee_name" type="search" placeholder="Enter employee name" aria-label="Search" required>

                            <div class="card mt-3 card-search-employee-result">
                                <div class="card-header card-header-search-employee">
                                    Results
                                </div>
                                <ul class="list-group list-group-flush list-group-employee">

                                </ul>
                            </div>

                    </div>
                    <div class="modal-footer">
                            <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
                            <button class="btn btn-dark my-2 my-sm-0 search-employee-btn" type="submit">Search</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>    

        <!-- End Modal Search Employee -->

    @endauth

    <div class="footer justify-content-center mt-5">
        <p class="text-center">Made with &hearts; by Fajar Hamdani</p>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.5.0.js" integrity="sha256-r/AaFHrszJtwpe+tHyNi/XCfMxYpbsRg2Uqn0x3s2zc=" crossorigin="anonymous"></script>    
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{ asset('js/app.js') }}"></script>
</body>
</html>